version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - '8000:8000'
    environment:
      - .env

  celery:
    build: .
    command: celery  -A video_crop worker --loglevel=info
    volumes:
      - .:/app/
    environment:
      - .env
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine